name: 'Version Retriever'
description: 'retrieve version from branch/tag name'
branding:
  color: white
  icon: git-branch
outputs:
  version:
    description: "version"
    value: ${{ steps.version-retriever.outputs.result }}
runs:
  using: "composite"
  steps: 
    - id: version-retriever
      run: |
        ref_name=${GITHUB_REF_NAME}
        ref_type=${GITHUB_REF_TYPE}
        echo "ref_name     => $ref_name"
        echo "ref_type     => $ref_type"
        if [[ $ref_name =~ [0-9]+(\\.[0-9]+)* ]]; 
        then
          echo "result=$(echo $ref_name)" >> $GITHUB_OUTPUT
        else
          echo "$ref_type $ref_name has invalid format"
          exit 1
        fi
      shell: bash
